### PR TITLE
Wrapped the code with an IIFE to make JS file bundling work

### PR DESCRIPTION
**Pull request by rohitpagariya**
Bundling of the app JS breaks because the code is not encapsulated in an [IIFE](http://en.wikipedia.org/wiki/Immediately-invoked_function_expression). This change fixes that.

### CODE REVIEW

**Comment by tedyoung** [comment]
I'm curious, what problem is this trying to solve? How are you "bundling" your app that requires this to be wrapped in an IIFE? I haven't had any problems using minification and concatenation tools to bundle this (and other directives) into a single file. The only issue I've had is that the 'use strict' needs a semi-colon at the end.

**Comment by rohitpagariya** [comment]
For some reason, concatenating the lib JS files is breaking my angular app. As part of the debugging, I realized this code is not wrapped in an IIFE which is generally a best practice. 

Having wrapped all my lib files in an IIFE fixed my app although I can't say for certain that this code was breaking it before. Hence this pull request.

**Comment by tedyoung** [comment]
Is it possible that something else is breaking things for you (and the IIFE is working around the problem), or are you actually encountering naming collisions? As I mentioned, in my build (I use the Grunt uglify task), I have no problems with unwrapped Angular modules.

Either way, you probably want to add a semi-colon in your line 35, i.e., it should be:
```
'use strict';
```

**Comment by rohitpagariya** [comment]
I managed to track down the bug, it was in another library I am using in my app. Incidentally, it was also not using an IIFE. 

I still think using an IIFE to encapsulate the code is a good practice, but I leave the final decision to accept the patch to you. Have a good weekend!

**Pull request closed without merging**
