### PR TITLE
group promised data

### PR DESCRIPTION
**Pull request by ericdouglas**

### CODE REVIEW

**Comment by nabinca** [comment]
Works like a charme! Thx

**Comment by ericdouglas** [comment]
@nabinca :smile:

**Comment by isteven** [comment]
Hi @ericdouglas , @nabinca, 

The reason I did not do this in the first place is that it's going to hit the performance once you put thousands of record in it. 

It "build" the grouping based on the filtered result, so there's way less data to iterate over :)

Anyway thanks for the PR, I'll see if I can find another way to achieve this. In the mean time I'll refer this PR to anyone who have similar question / request.

**Comment by ericdouglas** [comment]
Great @isteven ! Thanks for the feedback!

**Comment by isteven** [comment]
Covered in v3.0.0

**Pull request closed without merging**
