### PR TITLE
feat(select): add a custom title instead of 'none selected'

### PR DESCRIPTION
**Pull request by CaptainYouz**
Possibility to add a custom title instead of 'None selected' when no data are selected.
That avoid to put an other label to describe what the select box is for.

### CODE REVIEW

**Comment by tduchateau** [comment]
+1

**Comment by isteven** [comment]
All, 

if you read the "translation" part, you'll see that you can define a custom title / label when nothing is selected:

http://isteven.github.io/angular-multi-select/#/configs-options

**Comment by tduchateau** [comment]
I just stumbled on it. Thx! :-)

**Comment by isteven** [comment]
No problem. One caveat is that if you use the translation, you need to fill in all of the translation object properties (selectAll, selectNone etc) or else it will trigger some warnings.

**Comment by tduchateau** [comment]
Not a major issue in my opinion. Nevertheless, is it a technical limitation or rather a design issue?

**Comment by isteven** [comment]
That was me being absent minded :)

**Comment by tduchateau** [comment]
Ahah. Looking forward to the future release ;-)

Important to say: you did an amazing job on this component. Kudo!

**Comment by isteven** [comment]
Thank you for the kind words, glad the directive works for you.

**Pull request closed without merging**
